#!/usr/bin/expect

# Script used to initiate mavproxy connection from flight controller to GCS

# # Initialize gcs_ip with a default value
# set gcs_ip "10.13.0.4"

# # Try to get the WIFI_ENABLED environment variable directly using Tcl's env global array
# if {[info exists env(WIFI_ENABLED)]} {
#     if {$env(WIFI_ENABLED) eq "True"} {
#         set gcs_ip "192.168.13.14"
#     }
# }

# spawn mavproxy.py --master=/dev/ttyUSB0,57600 --out=udp:$gcs_ip:14550
# # Interact with MAVProxy as needed
# set timeout -1
# expect "xxxxx"
# send "xxxxx\r"
# interact