# SIMULATOR CONTAINER GAZEBO 11
# Use a lightweight base image like Ubuntu
FROM ubuntu:20.04

EXPOSE 8080 14550 14551

# Set environment variable to avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -y
RUN apt install lsb-release wget gnupg -y

RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null && \
    apt update -y && \
    apt install -y gazebo11 \
    libgazebo11-dev \
    git \
    npm \
    cmake \
    build-essential \
    rapidjson-dev \
    mercurial \
    libjansson-dev \
    imagemagick \
    libboost-dev \
    libtinyxml-dev \
    python2.7

# Install ArduPilot Gazebo Plugin
WORKDIR /Simulator
RUN git clone https://github.com/khancyr/ardupilot_gazebo && \
    cd ardupilot_gazebo && \
    mkdir build && cd build && \
    cmake .. && \
    make -j4
WORKDIR /Simulator

# Setup gazebo environment variables
ENV GAZEBO_MODEL_PATH /Simulator/ardupilot_gazebo/models:/usr/share/gazebo-11/models:${GAZEBO_MODEL_PATH}
ENV GAZEBO_RESOURCE_PATH /Simulator/ardupilot_gazebo/worlds:/usr/share/gazebo-11:/usr/share/gazebo-11/media:${GAZEBO_RESOURCE_PATH}
ENV GAZEBO_PLUGIN_PATH /Simulator/ardupilot_gazebo/build:/usr/lib/aarch64-linux-gnu/gazebo-11/plugins:${GAZEBO_PLUGIN_PATH}


# Install Node.js using Node Version Manager (NVM)
RUN apt-get update && apt-get install -y curl

RUN npm install -g n
RUN n 8.14.0

# Ignore git warnings
RUN git config --global advice.detachedHead false

# # Clone and build GzWeb
RUN git clone https://github.com/osrf/gzweb && \
    cd gzweb && \
    git checkout gzweb_1.4.1 && \
    /bin/bash -c "source /usr/share/gazebo/setup.sh && npm run deploy --- -m"

# Setup a virtual frame buffer
# RUN apt-get install -y xvfb
# RUN Xvfb :1 -screen 0 1600x1200x16 &
# ENV DISPLAY :1

# gzserver --verbose /Simulator/ardupilot_gazebo/worlds/iris_arducopter_runway.world
# cd /Simulator/gzweb && npm start

CMD tail -f /dev/null